name: Lint DID Method Registry
on:
  pull_request: {}

jobs:
  lint-did-spec-registries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code...
        uses: actions/checkout@v2
      - name: Setup Node 16...
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install did-spec-registries tooling...
        working-directory: tooling
        run: npm i
      - name: Validate did-spec-registries DID method entries
        working-directory: tooling
        run: npm run registry:validate
      - name: Generate did-spec-registries registry index
        working-directory: tooling
        run: npm run registry:generate:index
